server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: pgx
    source: postgres://db_admin:avito2025@127.0.0.1:5432/avito_shop
secrets:
  jwtKey: jslkjfljfljsflsjflskjf4u
